# Generated by Django 2.1 on 2018-08-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('cantidadPescadores', models.IntegerField()),
                ('cantidadClubes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviacion', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('hora', models.TimeField()),
                ('puntaje', models.FloatField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Campeonato')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Club')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.Torneo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='participantes',
            field=models.ManyToManyField(to='competencia.Participante'),
        ),
    ]
